//! Fixture-based tests against real PHPUnit output.
//!
//! `fixtures/phpunit-11.xml` was generated by PHPUnit 11.5 on PHP 8.4
//! (`phpunit --log-junit`); only the machine-specific path prefix was
//! rewritten to `/app`.

use kare_core::model::{Status, TestRun};
use kare_core::parser::junit::JunitParser;
use kare_core::parser::ReportParser;

const FIXTURE: &str = include_str!("fixtures/phpunit-11.xml");

fn parse(xml: &str) -> TestRun {
    JunitParser
        .parse(&mut xml.as_bytes())
        .expect("fixture must parse")
}

#[test]
fn parses_all_testcases_with_statuses() {
    let run = parse(FIXTURE);
    assert_eq!(run.results.len(), 8);

    let count = |s: Status| run.results.iter().filter(|r| r.status == s).count();
    assert_eq!(count(Status::Passed), 5);
    assert_eq!(count(Status::Failed), 1);
    assert_eq!(count(Status::Error), 1);
    assert_eq!(count(Status::Skipped), 1);

    // PHPUnit emits no timestamp; backfill relies on explicit overrides.
    assert_eq!(run.timestamp, None);
}

#[test]
fn canonical_ids_are_machine_independent_and_keep_data_sets() {
    let run = parse(FIXTURE);
    let ids: Vec<String> = run.results.iter().map(|r| r.canonical_id()).collect();

    // Identity comes from the class FQCN, never from surrounding suite
    // names, which contain absolute paths (`/app/phpunit.xml`).
    assert!(ids.iter().all(|id| !id.contains("/app")));
    assert!(ids.contains(&"Kare\\Fixture\\Sub\\StringUtilTest::testSlowOperation".to_string()));

    // Data provider cases stay distinct tests.
    assert!(ids.contains(
        &"Kare\\Fixture\\CalculatorTest::testWithProvider with data set \"zero\"".to_string()
    ));
    assert!(ids
        .contains(&"Kare\\Fixture\\CalculatorTest::testWithProvider with data set #0".to_string()));

    // Same input, same ids — required for tracking tests across runs.
    let ids_again: Vec<String> = parse(FIXTURE)
        .results
        .iter()
        .map(|r| r.canonical_id())
        .collect();
    assert_eq!(ids, ids_again);
}

#[test]
fn merge_combines_sharded_reports() {
    let shard_a = parse(FIXTURE);
    let shard_b = parse(FIXTURE);
    let merged = shard_a.merge(shard_b);
    assert_eq!(merged.results.len(), 16);
    assert!((merged.total_time_sec() - 2.0 * parse(FIXTURE).total_time_sec()).abs() < 1e-9);
}
